rm -rf ./gnuPar/*/splitSeq
rm -rf ./gnuPar/*/splitSeq2
rm -f ./gnuPar/*/filtered*
rm -f ./gnuPar/*/*.html
rm -f ./gnuPar/*/*.json
rm -f ./gnuPar/*/merged*
rm -f ./gnuPar/*/*virema*
rm -f ./gnuPar/*/*.txt
rm -f ./gnuPar/*/*.sam
rm -f ./gnuPar/*/*.bam
rm -f ./gnuPar/*/*.bam
rm -f ./gnuPar/*/samp_*